# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9eff5b8321d0e61c950dbf8c1202fe6f0d931ea5600bbf92e3d6f721270c1595ebb608d993ff8a97ef359074c76e5cf309ce8bc71f59620a6abb1da8506a35e

test:
  secret_key_base: bfdde3902ce3fc1f5016e2ea61e015f09f645b6b18b044c65ece3f4d4b1a63a81ec10e774235bee9408820e5834e88ea720e9a24f16ba4aeca469fd10c6d998c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
